---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
    state: fixed
    
- name: "install dependencies."
  become: true
  apt:
    name: ["python3-pip"]
    state: latest
    update_cache: yes
    
- name: "install pymongo"
  become: yes
  shell: |
   pip3 install pymongo
   
- name: Create MongoDB root user siteRootAdmin
  mongodb_user:
    login_user: "mongodb_admin_user"
    login_password: "mongodb_admin_password"
    login_port: "27017"
    database: "test"
    name: "mongodb_admin_user"
    password: "mongodb_admin_password"
    roles:
      -  {  db: "admin", role: "readWrite" }